name: mobivik
description: Mobivik, mobile assistant

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 0.6.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.7
  shared_preferences: ^0.5.7+1
  http:  ^0.12.0+1
  cupertino_icons: ^0.1.2
  intl: ^0.16.0
  package_info: ^0.4.0+18
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/favicon.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/svg/

